-- CRIANDO O BANCO DE DADOS
CREATE DATABASE LUTECH;

-- CRIANDO A PRIMEIRA COLUNA CHAMADA PROJETOS, COM TODOS OS ATRIBUTOS
CREATE TABLE PROJETOS (
    INDE_PROJ VARCHAR(50),
    END_PROJ VARCHAR(50),
    TEL_PROJ DECIMAL(11),
    TEL2_PROJ DECIMAL(11),
    STATUS_PROJ CHAR(3)
);
-- CRIANDO A SEGUNDA COLUNA CHAMADA DISP_ELETRONICO, COM TODOS OS ATRIBUTOS
CREATE TABLE DISP_ELETRONICO(
	ID_DIS VARCHAR(20),
    TIPO_DISP CHAR (10),
    MARCA CHAR (10)
);

-- CRIANDO A TERCEIRA COLUNA CHAMADA MANUTENCAO, COM 1 ATRIBUTO APENAS
CREATE TABLE MANUTENCAO(
	PECAS VARCHAR(20)
);

-- INSERINDO DADOS DENTRO DA COLUNA "PROJETOS"

INSERT INTO projetos (INDE_PROJ, END_PROJ, TEL_PROJ, STATUS_PROJ)
VALUES("Lívia Sarruf", null, 3299570234, "rec")

INSERT INTO projetos (INDE_PROJ, END_PROJ, TEL_PROJ, STATUS_PROJ)
VALUES ("Evandro_Miguel", "Santa_Luzia", 32984100646, "con");
-- INSERINDO DADOS DENTRO DA COLUNA "PROJETOS"
INSERT INTO projetos (INDE_PROJ, END_PROJ, TEL_PROJ, STATUS_PROJ)
VALUES ("Tayná", "Recanto_dos_Lagos", "32984217318", "rec");
-- INSERINDO DADOS DENTRO DA COLUNA "PROJETOS"
INSERT INTO projetos (INDE_PROJ, END_PROJ, TEL_PROJ, STATUS_PROJ)
VALUES ("Nathalia","Morro da Glória","32999053039","rec");

SHOW TABLES; -- COMANDO PARA VER AS TABELAS EXISTENTES
SHOW DATABASES; -- COMANDO PRA VER OS BANCOS DE DADOS EXISTENTES

ALTER TABLE projetos ADD PRIMARY KEY(INDE_PROJ); -- ADICIONANDO UMA CHAVE PRIMÁRIA DENTRO DA COLUNA PROJETOS
ALTER TABLE disp_eletronico ADD PRIMARY KEY (ID_DIS); -- ADICIONANDO UMA CHAVE PRIMÁRIA DENTRO DA COLUNA DISP_ELETRONICO

SET SQL_SAFE_UPDATES = 0; -- REMOVENDO A PROTEÇÃO DE SEGURANÇA DO BANCO DE DADOS

DELETE FROM PROJETOS WHERE STATUS_PROJ = "con";

ALTER TABLE PROJETOS
MODIFY COLUMN INDE_PROJ VARCHAR(50) NOT NULL;

ALTER TABLE PROJETOS
MODIFY COLUMN END_PROJ VARCHAR(50) NOT NULL;
