CREATE DATABASE LUTECH;

CREATE TABLE PROJETOS (
    INDE_PROJ VARCHAR(50),
    END_PROJ VARCHAR(50),
    TEL_PROJ DECIMAL(11),
    TEL2_PROJ DECIMAL(11),
    STATUS_PROJ CHAR(3)
);

CREATE TABLE DISP_ELETRONICO(
	ID_DIS VARCHAR(20),
    TIPO_DISP CHAR (10),
    MARCA CHAR (10)
);

CREATE TABLE MANUTENCAO(
	PECAS VARCHAR(20)
);

INSERT INTO projetos (INDE_PROJ, END_PROJ, TEL_PROJ)
VALUES ("Evandro_Miguel", "Santa_Luzia", 32984100646);

INSERT INTO projetos (status_proj)
VALUES ("con");

INSERT INTO projetos (INDE_PROJ, END_PROJ, TEL_PROJ, STATUS_PROJ)
VALUES ("Tayná", "XXX", "32984217318", "rec");

INSERT INTO projetos (INDE_PROJ, END_PROJ, TEL_PROJ, STATUS_PROJ)
VALUES ("Nathalia","Morro da Glória","32999053039","rec");